# Generated by Django 4.2.5 on 2023-10-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
