# Generated by Django 4.2.5 on 2023-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0002_alter_book_isbn_alter_book_year_bookstousers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0),
        ),
    ]
