# Generated by Django 4.2.7 on 2023-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserved_books',
            field=models.ManyToManyField(null=True, to='Richmond_Library_App.book'),
        ),
    ]
