# Generated by Django 4.2.7 on 2023-11-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0004_user_reserved_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksToUsers',
        ),
    ]
