# Generated by Django 4.2.5 on 2023-11-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0004_merge_0003_alter_book_isbn_0003_alter_user_user_type'),
        ('Richmond_Library_App', '0005_collection'),
    ]

    operations = [
    ]
