# Generated by Django 4.2.5 on 2023-10-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0005_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(null=True, to='Richmond_Library_App.book'),
        ),
    ]
