# Generated by Django 4.2.5 on 2023-11-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0006_alter_user_password'),
        ('Richmond_Library_App', '0006_merge_20231102_2249'),
    ]

    operations = [
    ]
