# Generated by Django 4.2.7 on 2023-11-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0008_book_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reserved_books',
            field=models.ManyToManyField(blank=True, null=True, to='Richmond_Library_App.book'),
        ),
    ]
