# Generated by Django 4.2.7 on 2023-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0009_alter_user_reserved_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkedout',
            field=models.BooleanField(default=False),
        ),
    ]
