# Generated by Django 4.2.5 on 2023-11-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0010_book_checkedout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkedout',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserved',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='available', max_length=100),
        ),
    ]
