# Generated by Django 4.2.7 on 2023-11-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0012_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default='student', max_length=10),
        ),
    ]
