# Generated by Django 4.2.5 on 2023-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Richmond_Library_App', '0013_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='static\\images\x08lank.png', null=True, upload_to='static\\images'),
        ),
    ]
